config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

  get 'welcome/blog'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/index'
  get 'welcome/proj1'
  get 'welcome/projects'
  get 'welcome/singlepost'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
	def about
	end
	def blog
	end
	def contact
	end
	def proj1
	end
	def projects
	end
	def singlepost
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpaceScience</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page">
<div id="header">
			<div>
				<a href="<%= welcome_index_path %>" class="logo"><%= image_tag("logo.png") %></a>
				<ul id="navigation">
					<li class="selected">
						<a href="<%= welcome_index_path %>">Home</a>
					</li>
					<li>
						<a href="<%= welcome_about_path %>">About</a>
					</li>
					<li class="menu">
						<a href="<%= welcome_projects_path %>">Projects</a>
						<ul class="primary">
							<li>
								<a href="<%= welcome_proj1_path %>">proj 1</a>
							</li>
						</ul>
					</li>
					<li class="menu">
						<a href="<%= welcome_blog_path %>">Blog</a>
						<ul class="secondary">
							<li>
								<a href="<%= welcome_singlepost_path %>">Single post</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="<%= welcome_contact_path %>">Contact</a>
					</li>
				</ul>
			</div>
		</div>

<%= yield %>

<div id="footer">
			<div class="connect">
				<div>
					<h1>FOLLOW OUR  MISSIONS ON</h1>
					<div>
						<a href="http://freewebsitetemplates.com/go/facebook/" class="facebook">facebook</a>
						<a href="http://freewebsitetemplates.com/go/twitter/" class="twitter">twitter</a>
						<a href="http://freewebsitetemplates.com/go/googleplus/" class="googleplus">googleplus</a>
						<a href="http://pinterest.com/fwtemplates/" class="pinterest">pinterest</a>
					</div>
				</div>
			</div>
			<div class="footnote">
				<div>
					<p>&copy; 2023 BY SPACE PROSPECTION | ALL RIGHTS RESERVED</p>
				</div>
			</div>
		</div>
	</div>

</body>
</html>